CREATE OR REPLACE PACKAGE PARADOX_REPORTS AUTHID CURRENT_USER

IS
 SQL1  LONG;


PROCEDURE DROP_TABLE(table_name VARCHAR2);
PROCEDURE R_NR1 (vDatastart VARCHAR2, sqlmaster out long);
PROCEDURE R_NR2;
PROCEDURE R_NR3;
PROCEDURE R_NR4 (Per1 VARCHAR2, OA VARCHAR2, Per2 VARCHAR2);
PROCEDURE R_NR5;
PROCEDURE R_NR6;


END PARADOX_REPORTS;
/